---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu servers
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages for RedHat/Rocky servers
    package:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Rocky"

